### ISSUE TITLE
swiss flag

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-jpo-landing#2]
the swiss flag should have the same size of the other flags
<img width="303" alt="schermata 2016-09-19 alle 13 06 40" src="https://cloud.githubusercontent.com/assets/19909772/18630018/fbc9c9a0-7e69-11e6-973d-5d65e5572e69.png">

**Comment by matthewmorek** [comment]
Unfortunately, I cannot alter it, as this is the official format of the Swiss country flag. http://www.wikiwand.com/en/Switzerland

**Comment by danielapizzurro** [comment]
Damn it! I was reading that the rectangular flag has also been used for e.g. at the Olympic games, but since we are a UN agency we better use the standard square format. So, I'm closing the issue.
