### ISSUE TITLE
fixes to md and sm media queries 

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-jpo-landing#3]
#### md - Chrome 53/Firefox 48/Opera 37+ W7 and Safari 6.2 + Mountain Lion
- [ ] rx box with video and 3-pieces section need some margin/padding
![md](https://cloud.githubusercontent.com/assets/19909772/18674432/834a4b08-7f4f-11e6-9842-dc56780ab4db.PNG)

#### sm- Chrome 53/Firefox 48/Opera 37+ W7 and Safari 6.2 + Mountain Lion
- [x] center the video
![sm](https://cloud.githubusercontent.com/assets/19909772/18674758/9966575a-7f50-11e6-9a6b-e6451c88f267.PNG)

**Comment by matthewmorek** [comment]
@danielapizzurro We won't be adding outer spacing for the three-piece section, for two reasons:
1. There is already inner padding being applied to elements inside the component;
2. We need to maximise space for content, and adding outer padding will compromise the content, by squishing it further.
